[package]
name = "rusty-sigil"
version = "0.1.0"
edition = "2021"

[build]
rustc-wrapper = "/home/isoosqa/.cargo/bin/sccache"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
